name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get install mingw-w64
        rustup target add x86_64-pc-windows-gnu
        cargo build --verbose --release --target x86_64-pc-windows-gnu
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: target/x86_64-pc-windows-gnu/release/sharpliner_task_codegen.exe